default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: matsunoring_development
test:
  <<: *default
  database: matsunoring_test
  
production:
  <<: *default
  database: matsunoring_production
  username: matsunoring
  password: <%= ENV['MATSUNORING_DATABASE_PASSWORD'] %>
